# Importing and installing libraries and packages

In [1]:
import pandas as pd
import numpy as np

df=pd.read_csv('truedata.csv')

In [2]:
df = df.dropna()

In [3]:
!pip install tensorflow
!pip install keras

Requirement already satisfied: tensorflow in c:\users\ankit\downloads\anaconda\lib\site-packages (2.11.0)
Requirement already satisfied: tensorflow-intel==2.11.0 in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorflow) (2.11.0)
Requirement already satisfied: keras<2.12,>=2.11.0 in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (2.11.0)
Requirement already satisfied: tensorflow-estimator<2.12,>=2.11.0 in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (2.11.0)
Requirement already satisfied: tensorboard<2.12,>=2.11 in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (2.11.2)
Requirement already satisfied: flatbuffers>=2.0 in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (23.3.3)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (1.51.3)
Requirement already satisfied: protobuf<3.20,>=3.9.2 in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (3.19.6)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (1.6.3)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (3.3.0)
Requirement already satisfied: numpy>=1.20 in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (1.21.5)
Requirement already satisfied: google-pasta>=0.1.1 in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (0.2.0)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (0.31.0)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (0.4.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (15.0.6.1)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (4.3.0)
Requirement already satisfied: six>=1.12.0 in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (2.2.0)
Requirement already satisfied: h5py>=2.9.0 in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (3.7.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (1.4.0)
Requirement already satisfied: packaging in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (21.3)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (1.14.1)
Requirement already satisfied: setuptools in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow) (63.4.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\ankit\downloads\anaconda\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.11.0->tensorflow) (0.37.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow) (2.28.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow) (0.4.6)
Requirement already satisfied: google-auth<3,>=1.6.3 in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow) (2.16.2)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow) (1.8.1)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow) (0.6.1)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow) (2.0.3)
Requirement already satisfied: markdown>=2.6.8 in c:\users\ankit\downloads\anaconda\lib\site-packages (from tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow) (3.3.4)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\ankit\downloads\anaconda\lib\site-packages (from packaging->tensorflow-intel==2.11.0->tensorflow) (3.0.9)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\ankit\downloads\anaconda\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow) (0.2.8)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\users\ankit\downloads\anaconda\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow) (5.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\ankit\downloads\anaconda\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\ankit\downloads\anaconda\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow) (1.3.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\ankit\downloads\anaconda\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow) (1.26.11)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ankit\downloads\anaconda\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ankit\downloads\anaconda\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow) (2022.9.14)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\ankit\downloads\anaconda\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow) (2.0.4)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\ankit\downloads\anaconda\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\ankit\downloads\anaconda\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.12,>=2.11->tensorflow-intel==2.11.0->tensorflow) (3.2.2)
Requirement already satisfied: keras in c:\users\ankit\downloads\anaconda\lib\site-packages (2.11.0)

In [5]:
df

,Strain Rate,Temperature,True Strain,True Stress,True Plastic Strain
0,0.0001,27.0,0.10683,939.31764,0.00030
1,0.0001,27.0,0.10683,939.32333,0.00030
2,0.0001,27.0,0.10684,939.33680,0.00031
3,0.0001,27.0,0.10684,939.34085,0.00031
4,0.0001,27.0,0.10685,939.34472,0.00032
...,...,...,...,...,...
162754,0.0100,500.0,0.06196,597.07372,0.01804
162755,0.0100,500.0,0.06218,597.09635,0.01826
162756,0.0100,500.0,0.06239,597.11009,0.01847
162757,0.0100,500.0,0.06260,597.11561,0.01868
162758,0.0100,500.0,0.06281,597.12663,0.01889

# Standardization, splitting the data

In [6]:
TargetVariable=['True Stress']
Predictors=['Strain Rate','Temperature','True Plastic Strain']
 
X=df[Predictors].values
y=df[TargetVariable].values
 
### Sandardization of data ###
from sklearn.preprocessing import StandardScaler
PredictorScaler=StandardScaler()
TargetVarScaler=StandardScaler()
 
# Storing the fit object for later reference
PredictorScalerFit=PredictorScaler.fit(X)
TargetVarScalerFit=TargetVarScaler.fit(y)
 
# Generating the standardized values of X and y
X=PredictorScalerFit.transform(X)
y=TargetVarScalerFit.transform(y)
 
# Split the data into training and testing set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
 
# Quick sanity check with the shapes of Training and testing datasets
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(113931, 3)
(113931, 1)
(48828, 3)
(48828, 1)

# Hyperparameter tuning and cross validation

In [12]:
# Function to generate Deep ANN model 
def make_regression_ann(learning_rate,dropout_rate):
    from keras.models import Sequential
    from keras.layers import Dense
    
    model = Sequential()
    model.add(Dense(units=5, input_dim=3, kernel_initializer='normal', activation='relu'))
    model.add(Dense(units=5, kernel_initializer='normal', activation='relu'))
    model.add(Dense(1, kernel_initializer='normal'))
    model.compile(loss='mean_squared_error', optimizer='adam')
    return model
 
###########################################
from sklearn.model_selection import GridSearchCV
from keras.wrappers.scikit_learn import KerasRegressor
 
# Listing all the parameters to try
Parameter_Trials={'batch_size':[20],
                  'epochs':[30],'learning_rate':[0.001,0.01,0.1],
                  'dropout_rate': [0.005,0.1,0.2]
                 }

filepath  = 'C:/Users/ankit/Downloads/Files for HPC'
from keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor = 'val_loss', patience=5)
from keras.callbacks import ModelCheckpoint
checkpoint = ModelCheckpoint(filepath, monitor='val_loss',mode='min',save_best_only=True,verbose=1)

 
# Creating the regression ANN model
RegModel=KerasRegressor(make_regression_ann, validation_split=0.25, verbose=0, callbacks=[early_stopping, checkpoint])
 
###########################################
from sklearn.metrics import make_scorer
 
# Defining a custom function to calculate accuracy
def Accuracy_Score(orig,pred):
    MAPE = np.mean(100 * (np.abs(orig-pred)/orig))
    print('#'*70,'Accuracy:', 100-MAPE)
    return(100-MAPE)
 
custom_Scoring=make_scorer(Accuracy_Score, greater_is_better=True)
 
#########################################
# Creating the Grid search space
# See different scoring methods by using sklearn.metrics.SCORERS.keys()
grid_search=GridSearchCV(estimator=RegModel, 
                         param_grid=Parameter_Trials, 
                         scoring=custom_Scoring, 
                         cv=10,n_jobs=-2)
 
#########################################
# Measuring how much time it took to find the best params
import time
StartTime=time.time()
 
# Running Grid Search for different paramenters
grid_search.fit(X,y, verbose=1)
 
EndTime=time.time()
print("########## Total Time Taken: ", round((EndTime-StartTime)/60), 'Minutes')
 
print('### Printing Best parameters ###')
grid_search.best_params_

C:\Users\ankit\AppData\Local\Temp\ipykernel_19616\615018142.py:31: DeprecationWarning: KerasRegressor is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  RegModel=KerasRegressor(make_regression_ann, validation_split=0.25, verbose=0, callbacks=[early_stopping, checkpoint])
C:\Users\ankit\Downloads\Anaconda\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning:
14 fits failed out of a total of 90.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\keras\wrappers\scikit_learn.py", line 175, in fit
    history = self.model.fit(x, y, **fit_args)
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\tensorflow\python\eager\execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: {{function_node __wrapped__SaveV2_dtypes_23_device_/job:localhost/replica:0/task:0/device:CPU:0}} Failed to rename: C:/Users/ankit/Downloads\Files for HPC\variables\variables_temp/part-00000-of-00001.index.tempstate487698117773563502 to: C:/Users/ankit/Downloads\Files for HPC\variables\variables_temp/part-00000-of-00001.index : Cannot create a file when that file already exists.
; Unknown error [Op:SaveV2]

--------------------------------------------------------------------------------
6 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\keras\wrappers\scikit_learn.py", line 175, in fit
    history = self.model.fit(x, y, **fit_args)
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\tensorflow\python\eager\execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError: {{function_node __wrapped__MergeV2Checkpoints_device_/job:localhost/replica:0/task:0/device:CPU:0}} Failed to rename: C:/Users/ankit/Downloads\Files for HPC\variables\variables_temp/part-00000-of-00001.data-00000-of-00001 to: C:/Users/ankit/Downloads\Files for HPC\variables\variables.data-00000-of-00001 : The system cannot find the file specified.
; No such file or directory [Op:MergeV2Checkpoints]

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\keras\wrappers\scikit_learn.py", line 175, in fit
    history = self.model.fit(x, y, **fit_args)
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\tensorflow\python\eager\execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: {{function_node __wrapped__MergeV2Checkpoints_device_/job:localhost/replica:0/task:0/device:CPU:0}} Failed to rename: C:/Users/ankit/Downloads\Files for HPC\variables\variables_temp/part-00000-of-00001.data-00000-of-00001 to: C:/Users/ankit/Downloads\Files for HPC\variables\variables.data-00000-of-00001 : Access is denied.
; Input/output error [Op:MergeV2Checkpoints]

--------------------------------------------------------------------------------
2 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\keras\wrappers\scikit_learn.py", line 175, in fit
    history = self.model.fit(x, y, **fit_args)
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\tensorflow\python\eager\execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__MergeV2Checkpoints_device_/job:localhost/replica:0/task:0/device:CPU:0}} allow_missing_files was set to false and C:/Users/ankit/Downloads\Files for HPC\variables\variables_temp/part-00000-of-00001 did not exist.NOT_FOUND: C:/Users/ankit/Downloads\Files for HPC\variables\variables_temp/part-00000-of-00001 not found [Op:MergeV2Checkpoints]

--------------------------------------------------------------------------------
2 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\keras\wrappers\scikit_learn.py", line 175, in fit
    history = self.model.fit(x, y, **fit_args)
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\tensorflow\python\eager\execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError: {{function_node __wrapped__MergeV2Checkpoints_device_/job:localhost/replica:0/task:0/device:CPU:0}} Failed to rename: C:/Users/ankit/Downloads\Files for HPC\variables\variables_temp/part-00000-of-00001.data-00000-of-00001 to: C:/Users/ankit/Downloads\Files for HPC\variables\variables.data-00000-of-00001 : The system cannot find the path specified.
; No such process [Op:MergeV2Checkpoints]

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\keras\wrappers\scikit_learn.py", line 175, in fit
    history = self.model.fit(x, y, **fit_args)
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 622, in rename_v2
    _pywrap_file_io.RenameFile(
tensorflow.python.framework.errors_impl.UnknownError: Failed to rename: C:/Users/ankit/Downloads\Files for HPC\fingerprint.pb.tmp721c00d2931848b3b0f467f6eada7e2c to: C:/Users/ankit/Downloads\Files for HPC\fingerprint.pb : Cannot create a file when that file already exists.
; Unknown error

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\keras\wrappers\scikit_learn.py", line 175, in fit
    history = self.model.fit(x, y, **fit_args)
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\ankit\Downloads\Anaconda\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 622, in rename_v2
    _pywrap_file_io.RenameFile(
tensorflow.python.framework.errors_impl.UnknownError: Failed to rename: C:/Users/ankit/Downloads\Files for HPC\fingerprint.pb.tmp7af383baa63f4edd85da0324e491651c to: C:/Users/ankit/Downloads\Files for HPC\fingerprint.pb : Cannot create a file when that file already exists.
; Unknown error

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\ankit\Downloads\Anaconda\lib\site-packages\sklearn\model_selection\_search.py:969: UserWarning: One or more of the test scores are non-finite: [         nan          nan 110.56947869 125.02812051 105.79788242
 116.14468507          nan          nan          nan]
  warnings.warn(

Epoch 1/30
6073/6104 [============================>.] - ETA: 0s - loss: 0.0823
Epoch 1: val_loss improved from inf to 1.64021, saving model to C:/Users/ankit/Downloads\Files for HPC

WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

6104/6104 [==============================] - 6s 886us/step - loss: 0.0820 - val_loss: 1.6402
Epoch 2/30
6099/6104 [============================>.] - ETA: 0s - loss: 0.0373
Epoch 2: val_loss did not improve from 1.64021
6104/6104 [==============================] - 5s 774us/step - loss: 0.0373 - val_loss: 1.6417
Epoch 3/30
6097/6104 [============================>.] - ETA: 0s - loss: 0.0373
Epoch 3: val_loss improved from 1.64021 to 1.63790, saving model to C:/Users/ankit/Downloads\Files for HPC

WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

6104/6104 [==============================] - 5s 891us/step - loss: 0.0373 - val_loss: 1.6379
Epoch 4/30
6092/6104 [============================>.] - ETA: 0s - loss: 0.0372
Epoch 4: val_loss did not improve from 1.63790
6104/6104 [==============================] - 5s 779us/step - loss: 0.0372 - val_loss: 1.6385
Epoch 5/30
6054/6104 [============================>.] - ETA: 0s - loss: 0.0372
Epoch 5: val_loss did not improve from 1.63790
6104/6104 [==============================] - 5s 769us/step - loss: 0.0372 - val_loss: 1.6426
Epoch 6/30
6070/6104 [============================>.] - ETA: 0s - loss: 0.0373
Epoch 6: val_loss improved from 1.63790 to 1.62633, saving model to C:/Users/ankit/Downloads\Files for HPC

WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

6104/6104 [==============================] - 5s 839us/step - loss: 0.0373 - val_loss: 1.6263
Epoch 7/30
6060/6104 [============================>.] - ETA: 0s - loss: 0.0372
Epoch 7: val_loss did not improve from 1.62633
6104/6104 [==============================] - 5s 767us/step - loss: 0.0372 - val_loss: 1.6291
Epoch 8/30
6061/6104 [============================>.] - ETA: 0s - loss: 0.0372
Epoch 8: val_loss did not improve from 1.62633
6104/6104 [==============================] - 5s 822us/step - loss: 0.0372 - val_loss: 1.6276
Epoch 9/30
6056/6104 [============================>.] - ETA: 0s - loss: 0.0372
Epoch 9: val_loss improved from 1.62633 to 1.62046, saving model to C:/Users/ankit/Downloads\Files for HPC

WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

6104/6104 [==============================] - 5s 872us/step - loss: 0.0372 - val_loss: 1.6205
Epoch 10/30
6102/6104 [============================>.] - ETA: 0s - loss: 0.0372
Epoch 10: val_loss improved from 1.62046 to 1.61998, saving model to C:/Users/ankit/Downloads\Files for HPC

WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

6104/6104 [==============================] - 5s 845us/step - loss: 0.0372 - val_loss: 1.6200
Epoch 11/30
6069/6104 [============================>.] - ETA: 0s - loss: 0.0372
Epoch 11: val_loss did not improve from 1.61998
6104/6104 [==============================] - 5s 766us/step - loss: 0.0372 - val_loss: 1.6287
Epoch 12/30
6077/6104 [============================>.] - ETA: 0s - loss: 0.0372
Epoch 12: val_loss improved from 1.61998 to 1.61189, saving model to C:/Users/ankit/Downloads\Files for HPC

WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

6104/6104 [==============================] - 5s 865us/step - loss: 0.0372 - val_loss: 1.6119
Epoch 13/30
6063/6104 [============================>.] - ETA: 0s - loss: 0.0372
Epoch 13: val_loss improved from 1.61189 to 1.60275, saving model to C:/Users/ankit/Downloads\Files for HPC

WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

6104/6104 [==============================] - 5s 833us/step - loss: 0.0372 - val_loss: 1.6027
Epoch 14/30
6099/6104 [============================>.] - ETA: 0s - loss: 0.0372
Epoch 14: val_loss improved from 1.60275 to 1.60174, saving model to C:/Users/ankit/Downloads\Files for HPC

WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

6104/6104 [==============================] - 5s 827us/step - loss: 0.0372 - val_loss: 1.6017
Epoch 15/30
6057/6104 [============================>.] - ETA: 0s - loss: 0.0372
Epoch 15: val_loss improved from 1.60174 to 1.59776, saving model to C:/Users/ankit/Downloads\Files for HPC

WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

6104/6104 [==============================] - 5s 875us/step - loss: 0.0372 - val_loss: 1.5978
Epoch 16/30
6073/6104 [============================>.] - ETA: 0s - loss: 0.0372
Epoch 16: val_loss improved from 1.59776 to 1.59259, saving model to C:/Users/ankit/Downloads\Files for HPC

WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

6104/6104 [==============================] - 5s 844us/step - loss: 0.0372 - val_loss: 1.5926
Epoch 17/30
6023/6104 [============================>.] - ETA: 0s - loss: 0.0372
Epoch 17: val_loss improved from 1.59259 to 1.58028, saving model to C:/Users/ankit/Downloads\Files for HPC

WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

6104/6104 [==============================] - 5s 879us/step - loss: 0.0372 - val_loss: 1.5803
Epoch 18/30
6076/6104 [============================>.] - ETA: 0s - loss: 0.0372
Epoch 18: val_loss improved from 1.58028 to 1.57491, saving model to C:/Users/ankit/Downloads\Files for HPC

WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

6104/6104 [==============================] - 5s 845us/step - loss: 0.0372 - val_loss: 1.5749
Epoch 19/30
6068/6104 [============================>.] - ETA: 0s - loss: 0.0371
Epoch 19: val_loss did not improve from 1.57491
6104/6104 [==============================] - 5s 782us/step - loss: 0.0372 - val_loss: 1.5767
Epoch 20/30
6038/6104 [============================>.] - ETA: 0s - loss: 0.0372
Epoch 20: val_loss improved from 1.57491 to 1.57325, saving model to C:/Users/ankit/Downloads\Files for HPC

WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

6104/6104 [==============================] - 5s 845us/step - loss: 0.0372 - val_loss: 1.5733
Epoch 21/30
6023/6104 [============================>.] - ETA: 0s - loss: 0.0372
Epoch 21: val_loss improved from 1.57325 to 1.57130, saving model to C:/Users/ankit/Downloads\Files for HPC

WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

6104/6104 [==============================] - 5s 828us/step - loss: 0.0372 - val_loss: 1.5713
Epoch 22/30
6057/6104 [============================>.] - ETA: 0s - loss: 0.0371
Epoch 22: val_loss did not improve from 1.57130
6104/6104 [==============================] - 5s 778us/step - loss: 0.0372 - val_loss: 1.5742
Epoch 23/30
6078/6104 [============================>.] - ETA: 0s - loss: 0.0372
Epoch 23: val_loss did not improve from 1.57130
6104/6104 [==============================] - 5s 808us/step - loss: 0.0372 - val_loss: 1.5767
Epoch 24/30
6089/6104 [============================>.] - ETA: 0s - loss: 0.0372
Epoch 24: val_loss did not improve from 1.57130
6104/6104 [==============================] - 5s 782us/step - loss: 0.0372 - val_loss: 1.5893
Epoch 25/30
6027/6104 [============================>.] - ETA: 0s - loss: 0.0371
Epoch 25: val_loss did not improve from 1.57130
6104/6104 [==============================] - 5s 772us/step - loss: 0.0372 - val_loss: 1.5885
Epoch 26/30
6049/6104 [============================>.] - ETA: 0s - loss: 0.0372
Epoch 26: val_loss did not improve from 1.57130
6104/6104 [==============================] - 5s 769us/step - loss: 0.0372 - val_loss: 1.5913
########## Total Time Taken:  44 Minutes
### Printing Best parameters ###

{'batch_size': 20, 'dropout_rate': 0.1, 'epochs': 30, 'learning_rate': 0.001}

# Fitting the model again with the best parameters, generate predictions and evaluating the model

In [15]:

# importing the libraries
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

filepath  = 'C:/Users/ankit/Downloads/Files for HPC'
from keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor = 'val_loss', patience=5)
from keras.callbacks import ModelCheckpoint
checkpoint = ModelCheckpoint(filepath, monitor='val_loss',mode='min',save_best_only=True,verbose=1)

# create ANN model
model = Sequential()
 
# Defining the Input layer and FIRST hidden layer, both are same!
model.add(Dense(units=5, input_dim=3, kernel_initializer='normal', activation='relu'))
model.add(Dropout(0.1))
# Defining the Second layer of the model
# after the first layer we don't have to specify input_dim as keras configure it automatically
model.add(Dense(units=5, kernel_initializer='normal', activation='relu'))
model.add(Dropout(0.1))
# The output neuron is a single fully connected node 
# Since we will be predicting a single number
model.add(Dense(1, kernel_initializer='normal'))
 
# Compiling the model
model.compile(loss='mean_squared_error', optimizer=keras.optimizers.Adam(learning_rate = 0.001))
 
# Fitting the ANN to the Training set
model.fit(X_train, y_train ,batch_size = 20, epochs = 30, validation_split=0.25, verbose=0, callbacks=[early_stopping, checkpoint])
 
# Generating Predictions on testing data
Predictions=model.predict(X_test)
 
# Scaling the predicted Price data back to original price scale
Predictions=TargetVarScalerFit.inverse_transform(Predictions)
 
# Scaling the y_test Price data back to original price scale
y_test_orig=TargetVarScalerFit.inverse_transform(y_test)
 
# Scaling the test data back to original scale
Test_Data=PredictorScalerFit.inverse_transform(X_test)
 
TestingData=pd.DataFrame(data=Test_Data, columns=Predictors)
TestingData['Stress']=y_test_orig
TestingData['Predicted Stress']=Predictions
TestingData

Epoch 1: val_loss improved from inf to 0.05199, saving model to C:/Users/ankit/Downloads\Files for HPC

WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

Epoch 2: val_loss improved from 0.05199 to 0.04412, saving model to C:/Users/ankit/Downloads\Files for HPC

WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

Epoch 3: val_loss improved from 0.04412 to 0.04151, saving model to C:/Users/ankit/Downloads\Files for HPC

WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

Epoch 4: val_loss improved from 0.04151 to 0.04034, saving model to C:/Users/ankit/Downloads\Files for HPC

WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

Epoch 5: val_loss did not improve from 0.04034

Epoch 6: val_loss did not improve from 0.04034

Epoch 7: val_loss improved from 0.04034 to 0.03891, saving model to C:/Users/ankit/Downloads\Files for HPC

WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

Epoch 8: val_loss did not improve from 0.03891

Epoch 9: val_loss did not improve from 0.03891

Epoch 10: val_loss did not improve from 0.03891

Epoch 11: val_loss improved from 0.03891 to 0.03696, saving model to C:/Users/ankit/Downloads\Files for HPC

WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

Epoch 12: val_loss improved from 0.03696 to 0.03619, saving model to C:/Users/ankit/Downloads\Files for HPC

WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

INFO:tensorflow:Assets written to: C:/Users/ankit/Downloads\Files for HPC\assets

Epoch 13: val_loss did not improve from 0.03619

Epoch 14: val_loss did not improve from 0.03619

Epoch 15: val_loss did not improve from 0.03619

Epoch 16: val_loss did not improve from 0.03619

Epoch 17: val_loss did not improve from 0.03619
1526/1526 [==============================] - 1s 488us/step

,Strain Rate,Temperature,True Plastic Strain,Stress,Predicted Stress
0,0.0001,100.0,0.00892,781.83656,767.241699
1,0.0001,300.0,0.01215,622.26907,672.584106
2,0.0001,200.0,0.02006,694.36165,712.741333
3,0.0001,500.0,0.01024,790.93119,817.324402
4,0.0001,400.0,0.02834,731.18290,739.924988
...,...,...,...,...,...
48823,0.0001,500.0,0.03309,917.60527,897.899963
48824,0.0001,100.0,0.00278,777.83329,754.005859
48825,0.0001,400.0,0.04224,740.82561,773.647217
48826,0.0010,500.0,0.11835,1152.24326,1117.856445
48827,0.0001,27.0,0.01595,950.02404,937.370056

In [18]:
# Computing the absolute percent error
APE=100*(abs(TestingData['Stress']-TestingData['Predicted Stress'])/TestingData['Stress'])
TestingData['APE']=APE
 
print('The Accuracy of ANN model is:', np.mean(APE))
TestingData

The Accuracy of ANN model is: 2.9844653926677136

,Strain Rate,Temperature,True Plastic Strain,Stress,Predicted Stress,APE
0,0.0001,100.0,0.00892,781.83656,767.241699,1.866741
1,0.0001,300.0,0.01215,622.26907,672.584106,8.085736
2,0.0001,200.0,0.02006,694.36165,712.741333,2.646990
3,0.0001,500.0,0.01024,790.93119,817.324402,3.336980
4,0.0001,400.0,0.02834,731.18290,739.924988,1.195609
...,...,...,...,...,...,...
48823,0.0001,500.0,0.03309,917.60527,897.899963,2.147471
48824,0.0001,100.0,0.00278,777.83329,754.005859,3.063308
48825,0.0001,400.0,0.04224,740.82561,773.647217,4.430409
48826,0.0010,500.0,0.11835,1152.24326,1117.856445,2.984336
48827,0.0001,27.0,0.01595,950.02404,937.370056,1.331965

In [19]:
# Computing the absolute percent error
APE=(abs(TestingData['Stress']-TestingData['Predicted Stress']))
TestingData['APE']=APE
 
print('The Accuracy of ANN model is:', np.mean(APE))
TestingData

The Accuracy of ANN model is: 23.282291048498003

,Strain Rate,Temperature,True Plastic Strain,Stress,Predicted Stress,APE
0,0.0001,100.0,0.00892,781.83656,767.241699,14.594861
1,0.0001,300.0,0.01215,622.26907,672.584106,50.315036
2,0.0001,200.0,0.02006,694.36165,712.741333,18.379683
3,0.0001,500.0,0.01024,790.93119,817.324402,26.393212
4,0.0001,400.0,0.02834,731.18290,739.924988,8.742088
...,...,...,...,...,...,...
48823,0.0001,500.0,0.03309,917.60527,897.899963,19.705307
48824,0.0001,100.0,0.00278,777.83329,754.005859,23.827431
48825,0.0001,400.0,0.04224,740.82561,773.647217,32.821607
48826,0.0010,500.0,0.11835,1152.24326,1117.856445,34.386815
48827,0.0001,27.0,0.01595,950.02404,937.370056,12.653984

In [20]:
import statistics
var = (statistics.variance(TestingData['Predicted Stress']))
print(var)
chi_sq = np.sum(((TestingData['Stress']-TestingData['Predicted Stress'])**2)/var)
red_chi_sq = chi_sq/5074
print('The reduced chi squared value for RFR is', red_chi_sq)

16944.086303533415
The reduced chi squared value for RFR is 0.5342657712656879

# Validating the model

In [21]:
dfvalid=pd.read_csv('150Cvalidationdata.csv')

In [22]:
dfvalid

,Strain Rate,Temperature,True Strain,True Stress,True Plastic Strain,Ridge Predicted Stress,RFR Predicted Stress,XGB Predicted Stress,SVR Predicted Stress
0,0.001,150,0.008686,649.481445,0.000062,633.142806,777.754361,624.89720,617.140417
1,0.001,150,0.008677,649.420837,0.000053,633.108214,777.754361,624.89720,617.104570
2,0.001,150,0.008694,649.400147,0.000070,633.172487,777.754361,624.89720,617.171199
3,0.001,150,0.008714,649.403870,0.000090,633.248762,777.754361,624.89720,617.250295
4,0.001,150,0.008722,649.421997,0.000097,633.276078,777.754361,624.89720,617.278739
...,...,...,...,...,...,...,...,...,...
5072,0.001,150,0.103290,700.204407,0.094666,988.512448,837.707106,756.38920,985.754788
5073,0.001,150,0.103298,700.248047,0.094674,988.542871,837.708480,756.38920,985.786345
5074,0.001,150,0.103348,700.315308,0.094723,988.728200,837.732867,756.38920,985.978581
5075,0.001,150,0.103320,700.301147,0.094695,988.623111,837.706032,756.38920,985.869576
5076,0.001,150,0.103368,700.319153,0.094744,988.805082,837.734023,757.15405,986.058328

In [23]:
Predictors=['Strain Rate','Temperature','True Plastic Strain']
X_valid=dfvalid[Predictors].values

In [24]:
X_valid

array([[1.0000000e-03, 1.5000000e+02, 6.1900000e-05],
       [1.0000000e-03, 1.5000000e+02, 5.2700000e-05],
       [1.0000000e-03, 1.5000000e+02, 6.9800000e-05],
       ...,
       [1.0000000e-03, 1.5000000e+02, 9.4723457e-02],
       [1.0000000e-03, 1.5000000e+02, 9.4695481e-02],
       [1.0000000e-03, 1.5000000e+02, 9.4743924e-02]])

In [25]:
from sklearn.preprocessing import StandardScaler
PredictorScaler=StandardScaler()
TargetVarScaler=StandardScaler()
 
# Storing the fit object for later reference
PredictorScalerFit=PredictorScaler.fit(X_valid)

# Generating the standardized values of X and y
X_valid=PredictorScalerFit.transform(X_valid)

In [26]:
X_valid

array([[-2.16840434e-19,  0.00000000e+00, -1.75357897e+00],
       [-2.16840434e-19,  0.00000000e+00, -1.75391575e+00],
       [-2.16840434e-19,  0.00000000e+00, -1.75328979e+00],
       ...,
       [-2.16840434e-19,  0.00000000e+00,  1.71155471e+00],
       [-2.16840434e-19,  0.00000000e+00,  1.71053064e+00],
       [-2.16840434e-19,  0.00000000e+00,  1.71230392e+00]])

In [27]:
y_pred_valid = model.predict(X_valid)

159/159 [==============================] - 0s 509us/step

In [28]:
y_pred_valid

array([[-1.2759032 ],
       [-1.2760446 ],
       [-1.2757816 ],
       ...,
       [-0.37425947],
       [-0.37425947],
       [-0.37425947]], dtype=float32)

In [29]:
y_pred_valid = TargetVarScalerFit.inverse_transform(y_pred_valid)

In [31]:
y_pred_valid

array([[619.0699],
       [619.0484],
       [619.0884],
       ...,
       [756.0348],
       [756.0348],
       [756.0348]], dtype=float32)

In [32]:
import pandas as pd 
pd.DataFrame(y_pred_valid).to_csv("annvalidationpredicteddata.csv")